export default {
  'PISTOL CROSSBOW': {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Crossbow_Hand_01.png',
    name: 'Pistol crossbow',
    scale: '1',
    useBolts: true,
    animation: 'Bolt01_01_Regular*',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  'REFLEX BOW': {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Longbow_01.png',
    scale: '1',
    name: 'Reflex bow',
    useArrows: true,
    animation: 'arrow01_01* -0.2 +0.5 ',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  STONE: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/stone.png',
    scale: '1',
    name: 'Stone',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  BOLT: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Crossbow_Bolt_01.png',
    scale: '1',
    name: 'Bolt',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  CLOAK: { texturePath: 'icons/equipment/back/cloakcollared-red-gold.webp', scale: '0.5', name: 'Cloak' },
  ARROW: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Arrow_01.png',
    scale: '1',
    name: 'Arrow',
  },

  BULLETS: { texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/bullets.png', scale: '1', name: 'bullets' },
  LONGBOW: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Longbow_01.png',
    scale: '1',
    name: 'Longbow',
    useArrows: true,
    animation: 'arrow01_01* -0.2 +0.5',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  SHORTBOW: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Longbow_01.png',
    scale: '1',
    name: 'Shortbow',
    useArrows: true,
    animation: 'arrow01_01* -0.2 +0.5',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  'REGULAR BOW': {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Longbow_01.png',
    scale: '1',
    name: 'Regular bow',
    useArrows: true,
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  'WALTHER PPK': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/Walter%20PPK.png',
    scale: '0.5',
    name: 'WalterPPK',
    useBullets: true,
    sound: 'dragupload/uploaded/ambient/Desert-Eagle-.50-AE-Close-Single-Gunshot-B-www.fesliyanstudios.com.mp3',
  },
  'IMI UZI': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/imi_uzi.png',
    scale: '1',
    name: 'ImiUzi',
    useBullets: true,
    animation: 'Bullet_02_Regular_Orange*',
    sound: 'dragupload/uploaded/ambient/Desert-Eagle-.50-AE-Close-Single-Gunshot-B-www.fesliyanstudios.com.mp3',
  },
  'LUGER P08': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/luger_p08.png',
    scale: '1',
    name: 'luger08',
    useBullets: true,
    animation: 'Bullet_02_Regular_Orange*',
    sound: 'dragupload/uploaded/ambient/Desert-Eagle-.50-AE-Close-Single-Gunshot-B-www.fesliyanstudios.com.mp3',
  },
  'SIG-SAUER P226': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/SIG_P226.png',
    scale: '0.5',
    speed: 0,
    name: 'sIGSauerP226',
    useBullets: true,
    animation: 'Bullet_02_Regular_Orange*',
    sound: 'dragupload/uploaded/ambient/Desert-Eagle-.50-AE-Close-Single-Gunshot-B-www.fesliyanstudios.com.mp3',
  },
  KATANA: {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/Katana.png',
    scale: '1',
    name: 'Katana',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  'ALS POCKET': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/ALS_Pocket_smoke.png',
    scale: '1',
    name: 'ALS_Pocket_smoke',
    animation: 'ThrowGrenade01_01_Regular_Green_05ft_600x400*',
  },
  'GLI-F4': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/GLI-F4.png',
    scale: '1',
    name: 'GLI-F4',
    animation: 'ThrowGrenade01_01_Regular_Green_05ft_600x400*',
  },
  'SCHERMULY STUN': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/Schermuly_Stun.png',
    scale: '1',
    name: 'Schermuly_Stun',
  },
  'LANZALLAMAS DE MANO': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/Hand_Flamethrower.png',
    scale: '1',
    name: 'Hand_Flamethrower',
  },
  'DIEHL DM51': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/Diehl_DM51.png',
    scale: '1',
    name: 'Diehl_DM51',
    animation: 'ThrowGrenade01_01_Regular_Green_05ft_600x400*',
  },
  'EXPANDABLE BATON': {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20modernas/extensible-baton.png',
    scale: '1',
    name: 'Expandable baton',
  },
  BLOWPIPE: {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20antiguas/blowpipe.png',
    scale: '1',
    name: 'Blowpipe',
  },
  POLTERGUEIST: {
    texturePath: 'moulinette/images/custom/JB2A/5th_Level/Arcane_Hand/ArcaneHand_Human_01_Idle_Rock01_Thumb.webp',
    scale: '1',
    animation: 'ProjectileIceShard01_01_Regular_Blue* -0.2 +0.5 ',
    name: 'Poltergueist',
    useMagic: true,
    costFatigue: 1,
    customManeuver: 'concentrate',
    ignoreOffHand: true,
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  MAGIC: {
    texturePath: 'moulinette/images/custom/JB2A/Generic/RangedSpell/ProjectileIceShard01_01_Regular_Blue_Thumb.webp',
    scale: '1',
    name: 'Arrow',
  },
  SLING: {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20antiguas/sling.webp',
    scale: '1',
    animation: 'arrow01_01* -0.2 +0.5 ',
    name: 'Sling',
    useStones: true,
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
  },
  SHURIKEN: {
    texturePath: 'icons/skills/ranged/shuriken-thrown-orange.webp',
    scale: '0.5',
    name: 'Shuriken',
    sound: 'modules/soundfxlibrary/Combat/Single/Throw Hit/throw-hit-1.mp3',
    animation: 'Kunai01_01_Regular_White*',
  },
  RAPIER: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Combat/Weapons/Swords/Rapier_A_01_1x1.png',
    scale: '1',
    name: 'Rapier',
    animation: 'Rapier01_01_Regular_White* c',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  MACE: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Mace_01.png',
    scale: '1',
    name: 'Mace',
    animation: 'Mace01_01_Regular_White_800x600* c',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-4.mp3',
  },
  KNIFE: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Dagger_01.png',
    scale: '1',
    name: 'Dagger',
    animation: 'Dagger01_01_Regular_White* c',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-2.mp3',
  },
  'THROWING KNIFE': {
    texturePath:
      'moulinette/images/custom/Forgotten-Adventures/Combat/Weapons/Special/Throwing_Knife_Metal_Gray_Black_A_1x1.png',
    scale: '1',
    name: 'Throwing knife',
    animation: 'Dagger01_01_Regular_White*',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-2.mp3',
  },
  SHORTSWORD: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Shortsword_01.png',
    scale: '1',
    name: 'Shortsword',
    animation: 'Sword01_01_Regular_White*',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  CUTLASS: {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20antiguas/cutlass.png',
    scale: '1',
    name: 'Cutlass',
    animation: 'Sword01_01_Regular_White*',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  FALCHION: {
    texturePath: 'moulinette/images/custom/Ludo/Armas%20antiguas/falcata.png',
    scale: '1',
    name: 'Falchion',
    animation: 'Falchion01_01_Regular_White*',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  BROADSWORD: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Longsword_01.png',
    scale: '1',
    name: 'Broadsword',
    animation: 'Sword01_01_Regular_White*',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  AXE: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Longsword_01.png',
    scale: '1',
    name: 'Broadsword',
    animation: 'Sword01_01_Regular_White*',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-8.mp3',
  },
  TORCH: {
    texturePath:
      'moulinette/images/custom/Forgotten-Adventures/Lightsources/Torches_and_Sconces/Torch_Hand_Wood_Ashen_B_1x1.png',
    scale: '1',
    name: 'Torch',
    animation: 'Mace01_01_Regular_White_800x600* c',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-4.mp3',
  },
  LANTERN: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Lightsources/Lanterns/Lantern_Metal_Brass_D2_1x1.png',
    scale: '1',
    name: 'Torch',
    animation: 'Mace01_01_Regular_White_800x600* c',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-4.mp3',
  },
  SPEAR: {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Weapons/Spear_A01.png',
    scale: '1',
    name: 'Spear',
    animation: 'Spear01_01_Regular_White_800x600* c',
    sound: 'modules/soundfxlibrary/Combat/Single/Melee Hit/melee-hit-10.mp3',
  },
  'SMALL SHIELD': {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Combat/Weapons/Shields/Shield_Metal_Gray_B_1x1.png',
    scale: '1',
    name: 'Small shield',
  },
  'MEDIUM SHIELD': {
    texturePath: 'moulinette/images/custom/Forgotten-Adventures/Combat/Weapons/Shields/Shield_Metal_Gray_A_1x1.png',
    scale: '1',
    name: 'Medium shield',
  },
  'LARGE SHIELD': {
    texturePath:
      'moulinette/images/custom/Forgotten-Adventures/Combat/Weapons/Shields/Shield_Metal_Gray_Gold_C_1x1.png',
    scale: '1',
    name: 'Large shield',
  },
};
